# task 1

I use numpy for the test only. That's because it is fast and correct. 
To check by numpy is more correct than to check by my own python code.

## sum test

In [1]:
import array
import task
import numpy as np #only use for tests

def test_matrix(test = 0):
    if test == 0:
        x = array.array("d", range(100))
        y = array.array("d", range(100))
    elif test == 1:
        x = [1, 2]
        x = [float(i) for i in x]
        y = [[1, 2], [1, 2]]
        y = [[float(i) for i in j] for j in y]
    elif test == 2:
        x = [[3, 2], [1, 8]]
        x = [[float(i) for i in j] for j in x]
        y = [[3, 2], [1, 8]]
        y = [[float(i) for i in j] for j in y]
    return x, y

def ans_test(answer, tes, test = 0):
    pre = 0
    if test == 0:
        #print(answer)
        #print(tes)
        for i in range(len(x)):
            if answer[i] == tes[i]:
                pre += 1
    elif test == 1:
        for i in range(len(answer)):
            if answer[i] == tes[i]:
                pre += 1
    else:
        for i in range(len(answer)):
            for j in range(len(answer[0])):
                if answer[i][j] == tes[i][j]:
                    pre += 1
        pre /= len(x)
    pre /= len(x)
    print(pre)

x, y = test_matrix(0)

In [2]:
#%timeit
#only use for tests
X = np.asarray(x)
Y = np.asarray(y)
answer = X + Y
answer

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100., 102., 104., 106., 108.,
       110., 112., 114., 116., 118., 120., 122., 124., 126., 128., 130.,
       132., 134., 136., 138., 140., 142., 144., 146., 148., 150., 152.,
       154., 156., 158., 160., 162., 164., 166., 168., 170., 172., 174.,
       176., 178., 180., 182., 184., 186., 188., 190., 192., 194., 196.,
       198.])

In [3]:
#%%timeit
tes = task.msum(x, y)
tes

[0.0,
 2.0,
 4.0,
 6.0,
 8.0,
 10.0,
 12.0,
 14.0,
 16.0,
 18.0,
 20.0,
 22.0,
 24.0,
 26.0,
 28.0,
 30.0,
 32.0,
 34.0,
 36.0,
 38.0,
 40.0,
 42.0,
 44.0,
 46.0,
 48.0,
 50.0,
 52.0,
 54.0,
 56.0,
 58.0,
 60.0,
 62.0,
 64.0,
 66.0,
 68.0,
 70.0,
 72.0,
 74.0,
 76.0,
 78.0,
 80.0,
 82.0,
 84.0,
 86.0,
 88.0,
 90.0,
 92.0,
 94.0,
 96.0,
 98.0,
 100.0,
 102.0,
 104.0,
 106.0,
 108.0,
 110.0,
 112.0,
 114.0,
 116.0,
 118.0,
 120.0,
 122.0,
 124.0,
 126.0,
 128.0,
 130.0,
 132.0,
 134.0,
 136.0,
 138.0,
 140.0,
 142.0,
 144.0,
 146.0,
 148.0,
 150.0,
 152.0,
 154.0,
 156.0,
 158.0,
 160.0,
 162.0,
 164.0,
 166.0,
 168.0,
 170.0,
 172.0,
 174.0,
 176.0,
 178.0,
 180.0,
 182.0,
 184.0,
 186.0,
 188.0,
 190.0,
 192.0,
 194.0,
 196.0,
 198.0]

In [4]:
ans_test(answer, tes, 0)

1.0


## prod test

In [5]:
#%%timeit
task.mprod(x, task.mpose(y))

[328350.0]

In [6]:
#%%timeit
tes = task.mprod(task.mpose(y), x)
tes

[[0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [0.0,
  1.0,
  2.0,
  3.0,
  4.0,
  5.0,
  6.0,
  7.0,
  8.0,
  9.0,
  10.0,
  11.0,
  12.0,
  13.0,
  14.0,
  15.0,
  16.0,
  17.0,
  18.0,
  19.0,
  20.0,
  21.0,
  22.0,
  23.0,
  24.0,
  25.0,
  26.0,
  27.0,
  28.0,
  29.0,
  30.0,
  31.0,
  32.0,
  33.0,
  34.0,
  35.0,
  36.0,
  37.0,
  38.

In [7]:
#%%timeit
X = np.asarray(x)
Y = np.asarray(y)
answer = np.dot(X.T.reshape(100, 1), Y.reshape(1, 100))
answer

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [0.000e+00, 1.000e+00, 2.000e+00, ..., 9.700e+01, 9.800e+01,
        9.900e+01],
       [0.000e+00, 2.000e+00, 4.000e+00, ..., 1.940e+02, 1.960e+02,
        1.980e+02],
       ...,
       [0.000e+00, 9.700e+01, 1.940e+02, ..., 9.409e+03, 9.506e+03,
        9.603e+03],
       [0.000e+00, 9.800e+01, 1.960e+02, ..., 9.506e+03, 9.604e+03,
        9.702e+03],
       [0.000e+00, 9.900e+01, 1.980e+02, ..., 9.603e+03, 9.702e+03,
        9.801e+03]])

In [8]:
ans_test(answer, tes, 2)

1.0


In [9]:
x, y = test_matrix(0)

In [10]:
tes = task.mprod(x, task.mpose(y))
X = np.asarray(x)
Y = np.asarray(y)
answer = X.dot(Y.T)
print(answer == tes)

x, y = test_matrix(2)
tes = task.mprod(x, y)
X = np.asarray(x)
Y = np.asarray(y)
answer = X.dot(Y)
ans_test(answer, tes, 2)
tes = task.mprod(y, task.mpose(x))
X = np.asarray(x)
Y = np.asarray(y)
answer = Y.dot(X.T)
ans_test(answer, tes, 2)

x, y = test_matrix(1)
tes = task.mprod(x, y)
X = np.asarray(x)
Y = np.asarray(y)
answer = X.dot(Y)
ans_test(answer, tes, 1)
x, y = test_matrix(1)
tes = task.mprod(y, task.mpose(x))
X = np.asarray(x)
Y = np.asarray(y)
answer = Y.dot(X.T)
ans_test(answer, tes, 1)

[ True]
1.0
1.0
1.0
1.0


## trans test

In [11]:
#%%timeit
x, y = test_matrix(0)
tes = task.mpose(x)
tes

[[0.0],
 [1.0],
 [2.0],
 [3.0],
 [4.0],
 [5.0],
 [6.0],
 [7.0],
 [8.0],
 [9.0],
 [10.0],
 [11.0],
 [12.0],
 [13.0],
 [14.0],
 [15.0],
 [16.0],
 [17.0],
 [18.0],
 [19.0],
 [20.0],
 [21.0],
 [22.0],
 [23.0],
 [24.0],
 [25.0],
 [26.0],
 [27.0],
 [28.0],
 [29.0],
 [30.0],
 [31.0],
 [32.0],
 [33.0],
 [34.0],
 [35.0],
 [36.0],
 [37.0],
 [38.0],
 [39.0],
 [40.0],
 [41.0],
 [42.0],
 [43.0],
 [44.0],
 [45.0],
 [46.0],
 [47.0],
 [48.0],
 [49.0],
 [50.0],
 [51.0],
 [52.0],
 [53.0],
 [54.0],
 [55.0],
 [56.0],
 [57.0],
 [58.0],
 [59.0],
 [60.0],
 [61.0],
 [62.0],
 [63.0],
 [64.0],
 [65.0],
 [66.0],
 [67.0],
 [68.0],
 [69.0],
 [70.0],
 [71.0],
 [72.0],
 [73.0],
 [74.0],
 [75.0],
 [76.0],
 [77.0],
 [78.0],
 [79.0],
 [80.0],
 [81.0],
 [82.0],
 [83.0],
 [84.0],
 [85.0],
 [86.0],
 [87.0],
 [88.0],
 [89.0],
 [90.0],
 [91.0],
 [92.0],
 [93.0],
 [94.0],
 [95.0],
 [96.0],
 [97.0],
 [98.0],
 [99.0]]

In [12]:
#ans_test does not coresspond to x in the case 1
ans_test(np.asarray(x).T, tes, 0)
ans_test(x, task.mpose(tes), 0)

1.0
1.0


## ReLU

In [13]:
x = range(-10, 10)
for i in x:
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
0
1
2
3
4
5
6
7
8
9


In [14]:
#%%timeit
x = array.array("d", x)
task.relu(x)

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0]

## Softmax

In [15]:
x = [i * 0.1 for i in range(0, 100)]

In [16]:
answer = np.exp(x) / np.sum(np.exp(x))
answer

array([4.77496908e-06, 5.27715696e-06, 5.83216040e-06, 6.44553406e-06,
       7.12341680e-06, 7.87259308e-06, 8.70056093e-06, 9.61560691e-06,
       1.06268891e-05, 1.17445288e-05, 1.29797117e-05, 1.43447999e-05,
       1.58534556e-05, 1.75207781e-05, 1.93634544e-05, 2.13999267e-05,
       2.36505767e-05, 2.61379295e-05, 2.88868796e-05, 3.19249392e-05,
       3.52825144e-05, 3.89932088e-05, 4.30941604e-05, 4.76264128e-05,
       5.26353263e-05, 5.81710319e-05, 6.42889328e-05, 7.10502589e-05,
       7.85226798e-05, 8.67809821e-05, 9.59078177e-05, 1.05994531e-04,
       1.17142073e-04, 1.29462012e-04, 1.43077651e-04, 1.58125259e-04,
       1.74755438e-04, 1.93134628e-04, 2.13446774e-04, 2.35895167e-04,
       2.60704478e-04, 2.88123007e-04, 3.18425169e-04, 3.51914236e-04,
       3.88925379e-04, 4.29829018e-04, 4.75034531e-04, 5.24994349e-04,
       5.80208486e-04, 6.41229545e-04, 7.08668245e-04, 7.83199535e-04,
       8.65569349e-04, 9.56602073e-04, 1.05720879e-03, 1.16839641e-03,
      

In [17]:
tes = task.softmax(x)
tes

[4.7749690769511605e-06,
 5.277156958556943e-06,
 5.832160400717668e-06,
 6.445534064425583e-06,
 7.123416799469081e-06,
 7.872593084104736e-06,
 8.700560926396026e-06,
 9.615606906798203e-06,
 1.0626889113040709e-05,
 1.1744528797347305e-05,
 1.29797116733302e-05,
 1.434479986637154e-05,
 1.5853455637929264e-05,
 1.7520778122041835e-05,
 1.9363454442536696e-05,
 2.1399926723374254e-05,
 2.3650576663623112e-05,
 2.6137929524354847e-05,
 2.888687956902782e-05,
 3.1924939213643146e-05,
 3.5282514380251235e-05,
 3.89932088096395e-05,
 4.3094160378864714e-05,
 4.762641278960912e-05,
 5.263532634734208e-05,
 5.817103194250335e-05,
 6.428893277730427e-05,
 7.105025885959696e-05,
 7.852267981337319e-05,
 8.678098213910578e-05,
 9.590781770218187e-05,
 0.0001059945309405522,
 0.00011714207307056773,
 0.00012946201244068393,
 0.0001430776511449916,
 0.00015812525907201754,
 0.00017475543773957125,
 0.00019313462756535369,
 0.00021344677365860024,
 0.00023589516680456017,
 0.00026070447806700374

In [18]:
ans_test(answer, tes, 1)

1.0
